cc_test(
    name = "valid_sudoku_test",
    srcs = ["valid_sudoku_test.cpp"],
    deps = [
        "@gtest//:gtest",
        "@gtest//:gtest_main",
        ":valid_sudoku"
    ]
)

cc_library(
    name = "valid_sudoku",
    srcs = ["valid_sudoku.hpp"]
)