cc_test(
    name = "two_sum_test",
    srcs = ["two_sum_test.cpp"],
    deps = [
        "@gtest//:gtest",
        "@gtest//:gtest_main",
        ":two_sum"
    ]
)

cc_library(
    name = "two_sum",
    srcs = ["two_sum.hpp"]
)